services:
  animaldex:
    build: .
    # image: ghcr.io/romain-drsl/animaldex:latest
    container_name: animaldex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.animaldex.rule=Host(`animaldex.localhost`) || Host(`localhost`)"
      - "traefik.http.routers.animaldex.entrypoints=web"
      - "traefik.http.services.animaldex.loadbalancer.server.port=8080"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
